# Словарь с немецкими словами уровня а1
german_a1_to_russian = {
    "hallo": "привет",
    "gut": "хорошо",
    "danke": "спасибо",
    "bitte": "пожалуйста",
    "ja": "да",
    "nein": "нет",
    "schule": "школа",
    "buch": "книга",
    "stuhl": "стул",
    "tisch": "стол",
    "hund": "собака",
    "katze": "кошка",
    "maus": "мышь",
    "vogel": "птица",
    "haus": "дом",
    "auto": "автомобиль",
    "apfel": "яблоко",
    "banane": "банан",
    "kuchen": "пирог",
    "brot": "хлеб",
    "milch": "молоко",
    "kaffee": "кофе",
    "tee": "чай",
    "wasser": "вода",
    "essen": "еда",
    "trinken": "пить",
    "spielen": "играть",
    "lernen": "учиться",
    "verstehen": "понимать",
    "sprechen": "говорить",
    "heißen": "зваться",
    "kommen": "приходить",
    "gehen": "идти",
    "sehen": "видеть",
    "hören": "слышать",
    "lesen": "читать",
    "schreiben": "писать",
    "mögen": "нравиться",
    "lieben": "любить",
    "haben": "иметь",
    "sein": "быть",
    "machen": "делать",
    "wollen": "хотеть",
    "können": "мочь",
    "müssen": "должен",
    "dürfen": "иметь разрешение",
    "wissen": "знать",
    "arbeiten": "работать",
    "wohnen": "жить",
    "fahren": "ехать",
    "leben": "жить",
    "warten": "ждать",
    "fragen": "спрашивать",
    "antworten": "отвечать",
    "kaufen": "покупать",
    "verkaufen": "продавать",
    "finden": "находить",
    "verlieren": "терять",
    "mieten": "снимать (например, квартиру)",
    "anrufen": "звонить по телефону",
    "kennen": "знать, быть знакомым",
    "schlafen": "спать",
    "öffnen": "открывать",
    "schließen": "закрывать",
    "laufen": "бежать",
    "bleiben": "оставаться",
    "helfen": "помогать",
    "beginnen": "начинать",
    "enden": "заканчивать",
    "fühlen": "чувствовать",
    "sollen": "должен",
    "früh": "рано",
    "spät": "поздно",
    "heute": "сегодня",
    "morgen": "завтра",
    "gestern": "вчера",
    "Montag": "понедельник",
    "Dienstag": "вторник",
    "Mittwoch": "среда",
    "Donnerstag": "четверг",
    "Freitag": "пятница",
    "Samstag": "суббота",
    "Sonntag": "воскресенье",
    "Januar": "январь",
    "Februar": "февраль",
    "März": "март",
    "April": "апрель",
    "Mai": "май",
    "Juni": "июнь",
    "Juli": "июль",
    "August": "август",
    "September": "сентябрь",
    "Oktober": "октябрь",
    "November": "ноябрь",
    "Dezember": "декабрь",
    "Frühling": "весна",
    "Sommer": "лето",
    "Herbst": "осень",
    "Winter": "зима",
    "schön": "красивый",
    "hässlich": "уродливый",
    "groß": "большой",
    "klein": "маленький",
    "alt": "старый",
    "jung": "молодой",
    "schlecht": "плохой",
    "warm": "теплый",
    "kalt": "холодный",
    "leicht": "легкий",
    "schwer": "тяжелый",
    "teuer": "дорогой",
    "billig": "дешевый",
    "richtig": "правильный",
    "falsch": "неправильный",
    "neu": "новый",
    "interessant": "интересный",
    "langweilig": "скучный",
    "schwierig": "сложный",
    "einfach": "простой",
    "gern": "с удовольствием",
    "nicht gern": "неохотно",
    "oft": "часто",
    "manchmal": "иногда",
    "selten": "редко",
    "jetzt": "сейчас",
    "gleich": "сразу",
    "noch": "еще",
    "immer": "всегда",
    "nie": "никогда",
    "viel": "много",
    "wenig": "мало",
    "genug": "достаточно",
    "alle": "все",
    "keine": "ничего",
    "einige": "несколько",
    "mehrere": "несколько",
    "anderer": "другой",
    "dieser": "этот",
    "jeder": "каждый",
    "keiner": "никто",
    "welcher": "который",
    "mein": "мой",
    "dein": "твой",
    "unser": "наш",
    "euer": "ваш",
    "ihr": "их",
    "wie": "как",
    "wer": "кто",
    "was": "что",
    "wo": "где",
    "wann": "когда",
    "warum": "почему",
    "wie viel": "сколько",
    "wohin": "куда",
    "woher": "откуда",
    "weil": "потому что",
    "dass": "что (вводное слово)",
    "und": "и",
    "oder": "или",
    "aber": "но",
    "denn": "ведь",
    "also": "так что",
    "vielleicht": "возможно",
    "entschuldigung": "извините",
    "auf wiedersehen": "до свидания",
    "gern geschehen": "пожалуйста (ответ на спасибо)"
}

# Словарь с немецкими словами уровня а2
german_a2_to_russian = {
    "verstehen": "понимать",
    "sprechen": "говорить",
    "heißen": "зваться",
    "kommen": "приходить",
    "gehen": "идти",
    "sehen": "видеть",
    "hören": "слышать",
    "lesen": "читать",
    "schreiben": "писать",
    "mögen": "нравиться",
    "lieben": "любить",
    "haben": "иметь",
    "sein": "быть",
    "machen": "делать",
    "wollen": "хотеть",
    "können": "мочь",
    "müssen": "должен",
    "dürfen": "иметь разрешение",
    "wissen": "знать",
    "arbeiten": "работать",
    "wohnen": "жить",
    "fahren": "ехать",
    "leben": "жить",
    "warten": "ждать",
    "fragen": "спрашивать",
    "antworten": "отвечать",
    "kaufen": "покупать",
    "verkaufen": "продавать",
    "finden": "находить",
    "verlieren": "терять",
    "mieten": "снимать (например, квартиру)",
    "anrufen": "звонить по телефону",
    "kennen": "знать, быть знакомым",
    "lernen": "учить",
    "schlafen": "спать",
    "öffnen": "открывать",
    "schließen": "закрывать",
    "laufen": "бежать",
    "bleiben": "оставаться",
    "helfen": "помогать",
    "beginnen": "начинать",
    "enden": "заканчивать",
    "fühlen": "чувствовать",
    "sollen": "должен",
    "früh": "рано",
    "spät": "поздно",
    "heute": "сегодня",
    "morgen": "завтра",
    "gestern": "вчера",
    "Montag": "понедельник",
    "Dienstag": "вторник",
    "Mittwoch": "среда",
    "Donnerstag": "четверг",
    "Freitag": "пятница",
    "Samstag": "суббота",
    "Sonntag": "воскресенье",
    "Januar": "январь",
    "Februar": "февраль",
    "März": "март",
    "April": "апрель",
    "Mai": "май",
    "Juni": "июнь",
    "Juli": "июль",
    "August": "август",
    "September": "сентябрь",
    "Oktober": "октябрь",
    "November": "ноябрь",
    "Dezember": "декабрь",
    "Frühling": "весна",
    "Sommer": "лето",
    "Herbst": "осень",
    "Winter": "зима",
    "schön": "красивый",
    "hässlich": "уродливый",
    "groß": "большой",
    "klein": "маленький",
    "alt": "старый",
    "jung": "молодой",
    "gut": "хороший",
    "schlecht": "плохой",
    "warm": "теплый",
    "kalt": "холодный",
    "leicht": "легкий",
    "schwer": "тяжелый",
    "teuer": "дорогой",
    "billig": "дешевый",
    "richtig": "правильный",
    "falsch": "неправильный",
    "neu": "новый",
    "interessant": "интересный",
    "langweilig": "скучный",
    "schwierig": "сложный",
    "einfach": "простой",
    "gern": "с удовольствием",
    "nicht gern": "неохотно",
    "oft": "часто",
    "manchmal": "иногда",
    "selten": "редко",
    "vielleicht": "возможно",
    "jetzt": "сейчас",
    "gleich": "сразу",
    "noch": "еще",
    "immer": "всегда",
    "nie": "никогда",
    "viel": "много",
    "wenig": "мало",
    "genug": "достаточно",
    "alle": "все",
    "keine": "ничего",
    "einige": "несколько",
    "mehrere": "несколько",
    "anderer": "другой",
    "dieser": "этот",
    "jeder": "каждый",
    "keiner": "никто",
    "welcher": "который",
    "mein": "мой",
    "dein": "твой",
    "ihr": "их",
    "unser": "наш",
    "euer": "ваш",
    "wie": "как",
    "wer": "кто",
    "was": "что",
    "wo": "где",
    "wann": "когда",
    "warum": "почему",
    "wie viel": "сколько",
    "wohin": "куда",
    "woher": "откуда",
    "weil": "потому что",
    "dass": "что (вводное слово)",
    "und": "и",
    "oder": "или",
    "aber": "но",
    "denn": "ведь",
    "also": "так что",
    "ja": "да",
    "nein": "нет",
    "bitte": "пожалуйста",
    "danke": "спасибо",
    "entschuldigung": "извините",
    "auf wiedersehen": "до свидания",
    "gern geschehen": "пожалуйста (ответ на спасибо)",
    "mehr": "больше",
    "weniger": "меньше",
    "anders": "по-другому",
    "noch nicht": "еще не",
    "schon": "уже",
    "nochmal": "еще раз",
    "bitte schön": "пожалуйста",
    "natürlich": "конечно",
    "nur": "только",
    "überall": "везде",
    "irgendwo": "где-то",
    "bald": "скоро",
    "dann": "потом",
    "vorher": "раньше",
    "heute Morgen": "сегодня утром",
    "gestern Abend": "вчера вечером",
    "am Wochenende": "на выходных",
    "im Moment": "в данный момент",
    "zu Hause": "дома",
    "in der Schule": "в школе",
    "im Büro": "в офисе",
    "in der Stadt": "в городе",
    "im Supermarkt": "в супермаркете",
    "in der Nähe": "рядом",
    "weit weg": "далеко",
    "im Ausland": "за границей",
    "im Urlaub": "на отдыхе",
    "im Restaurant": "в ресторане",
    "am Strand": "на пляже",
    "im Park": "в парке",
    "im Kino": "в кино",
    "im Krankenhaus": "в больнице",
    "im Hotel": "в отеле",
    "am Flughafen": "в аэропорту",
    "in der Bibliothek": "в библиотеке",
    "in der Kirche": "в церкви",
    "im Museum": "в музее",
    "im Zoo": "в зоопарке",
    "im Schwimmbad": "в бассейне",
    "im Fitnessstudio": "в фитнес-клубе",
    "im Theater": "в театре",
    "im Café": "в кафе",
    "im Garten": "в саду",
    "im Bus": "в автобусе",
    "im Zug": "в поезде",
    "im Auto": "в машине",
    "zu Fuß": "пешком",
    "mit dem Fahrrad": "на велосипеде",
    "mit dem Motorrad": "на мотоцикле",
    "mit dem Auto": "на машине",
    "mit dem Zug": "на поезде",
    "mit dem Flugzeug": "на самолете",
    "mit dem Bus": "на автобусе",
    "mit der Straßenbahn": "на трамвае",
    "mit der U-Bahn": "на метро",
    "mit dem Boot": "на лодке",
    "mit dem Schiff": "на корабле",
    "zu Hause bleiben": "оставаться дома",
    "einkaufen gehen": "идти за покупками",
    "einen Spaziergang machen": "прогуливаться",
    "sich ausruhen": "отдыхать",
    "Sport treiben": "заниматься спортом",
    "Fernsehen schauen": "смотреть телевизор",
    "kochen": "готовить",
    "aufräumen": "убираться",
    "staubsaugen": "пылесосить",
    "spülen": "мыть посуду",
    "waschen": "стирать",
    "bügeln": "гладить",
    "putzen": "чистить",
    "den Müll wegbringen": "выносить мусор",
    "Blumen gießen": "поливать цветы",
    "den Rasen mähen": "косить газон",
    "das Bett machen": "заправлять кровать",
    "die Wäsche aufhängen": "вешать белье",
    "Musik hören": "слушать музыку",
    "ein Buch lesen": "читать книгу",
    "einen Film sehen": "смотреть фильм",
    "Fotos machen": "делать фотографии",
    "Fotos anschauen": "смотреть фотографии",
    "eine Sprache lernen": "изучать язык",
    "Briefe schreiben": "писать письма",
    "sich mit Freunden treffen": "встречаться с друзьями",
    "ins Kino gehen": "ходить в кино",
    "in einem Restaurant essen gehen": "есть в ресторане"
}

# Словарь с немецкими словами уровня b1
german_b1_to_russian = {
    "vermutlich": "вероятно",
    "vorhanden": "наличный",
    "begeistert": "восторженный",
    "überwinden": "преодолеть",
    "entscheiden": "решить",
    "gewöhnlich": "обычный",
    "herausfordernd": "сложный",
    "außergewöhnlich": "необычный",
    "zusammenhängen": "связывать",
    "ausreichend": "достаточный",
    "verantwortlich": "ответственный",
    "beziehungsweise": "соответственно",
    "eigentlich": "собственно",
    "geduldig": "терпеливый",
    "nachdenken": "обдумывать",
    "widersprechen": "противоречить",
    "zwischenmenschlich": "межличностный",
    "abhängen": "зависеть",
    "zusätzlich": "дополнительный",
    "bequem": "удобный",
    "empfehlenswert": "рекомендуемый",
    "verschieden": "различный",
    "beabsichtigen": "намереваться",
    "überraschend": "неожиданный",
    "gewissermaßen": "по сути",
    "ausdrücklich": "явно",
    "voraussichtlich": "предполагаемый",
    "aufrichtig": "искренний",
    "wahrscheinlich": "вероятный",
    "anstrengend": "напряженный",
    "sorgfältig": "тщательный",
    "vergleichsweise": "относительно",
    "gründlich": "основательный",
    "bemerken": "замечать",
    "häufig": "часто",
    "tatsächlich": "фактически",
    "üblich": "обычный",
    "ernsthaft": "серьезно",
    "bevorzugen": "предпочитать",
    "dementsprechend": "соответственно",
    "hervorragend": "превосходный",
    "ungefähr": "примерно",
    "trotzdem": "тем не менее",
    "vorwiegend": "преимущественно",
    "abwechslungsreich": "разнообразный",
    "bezüglich": "относительно",
    "widersprüchlich": "противоречивый",
    "ziemlich": "довольно",
    "bejahen": "утвердительно ответить",
    "möglicherweise": "возможно",
    "unterstützen": "поддерживать",
    "kürzlich": "недавно",
    "darstellen": "представлять",
    "ungeachtet": "несмотря на",
    "beträchtlich": "значительный",
    "entsprechend": "соответствующий",
    "eigensinnig": "упрямый",
    "zunächst": "прежде всего",
    "anscheinend": "видимо",
    "völlig": "полностью",
    "absolut": "абсолютный",
    "dringend": "срочно",
    "einzigartig": "уникальный",
    "angeblich": "якобы",
    "anerkennen": "признавать",
    "anstreben": "стремиться",
    "begrüßen": "приветствовать",
    "beschließen": "решать",
    "betonen": "подчеркивать",
    "bewerten": "оценивать",
    "bieten": "предлагать",
    "entwickeln": "разрабатывать",
    "erhöhen": "повышать",
    "erklären": "объяснять",
    "fördern": "способствовать",
    "gewährleisten": "гарантировать",
    "gründen": "основывать",
    "hervorrufen": "вызывать",
    "überzeugen": "убеждать",
    "verbinden": "соединять",
    "voraussehen": "предвидеть",
    "widerspiegeln": "отражать",
    "zustimmen": "соглашаться",
    "der Anlass": "повод",
    "der Anstand": "приличие",
    "die Anzeige": "объявление",
    "die Ausdauer": "выносливость",
    "die Aussicht": "перспектива",
    "die Bedingung": "условие",
    "die Begeisterung": "восторг",
    "die Behinderung": "инвалидность",
    "die Belastung": "нагрузка",
    "die Bereicherung": "обогащение",
    "die Bescheinigung": "удостоверение",
    "die Besorgnis": "беспокойство",
    "die Bestätigung": "подтверждение",
    "die Beziehung": "отношение",
    "die Einsicht": "понимание",
    "die Entschädigung": "компенсация",
    "die Enttäuschung": "разочарование",
    "die Erfahrung": "опыт",
    "die Erholung": "отдых",
    "die Erlaubnis": "разрешение",
    "die Erschöpfung": "истощение",
    "die Erwartung": "ожидание",
    "die Förderung": "поощрение",
    "die Geduld": "терпение",
    "die Genehmigung": "разрешение",
    "die Gewohnheit": "привычка",
    "die Grundlage": "основание",
    "die Herausforderung": "вызов",
    "die Hinsicht": "отношение",
    "die Hoffnung": "надежда",
    "die Kenntnis": "знание",
    "die Kompensation": "компенсация",
    "die Konkurrenz": "конкуренция",
    "die Leidenschaft": "страсть",
    "die Nachfrage": "спрос",
    "die Rücksicht": "учет",
    "die Rücksichtnahme": "учет",
    "die Tatsache": "факт",
    "die Überzeugung": "убеждение",
    "die Ungeduld": "нетерпение",
    "die Veränderung": "изменение",
    "die Voraussetzung": "предпосылка",
    "die Vorliebe": "предпочтение",
    "die Vorsicht": "осторожность",
    "die Vorsichtsmaßnahme": "мера предосторожности",
    "die Vorschrift": "инструкция",
    "die Wertschätzung": "оценка",
    "die Wirkung": "действие",
    "die Zuneigung": "привязанность",
    "die Zuvorkommenheit": "учтивость",
    "die Zuversicht": "уверенность",
    "die Zweckmäßigkeit": "целесообразность",
    "der Ansatz": "подход",
    "der Aufwand": "затраты",
    "der Ausgleich": "компенсация",
    "der Auslöser": "спусковой крючок",
    "der Bedarf": "потребность",
    "der Bedauern": "сожаление",
    "der Behälter": "контейнер",
    "der Behelf": "провизорий",
    "der Beleg": "чек",
    "der Beobachter": "наблюдатель",
    "der Betrag": "сумма",
    "der Beweis": "доказательство",
    "der Ehrgeiz": "амбиция",
    "der Einsatz": "использование",
    "der Entschluss": "решение",
    "der Ersatz": "замена",
    "der Erwerb": "приобретение",
    "der Fortschritt": "прогресс",
    "der Gegenstand": "предмет",
    "der Gegensatz": "противоположность",
    "der Glaube": "вера",
    "der Grad": "степень",
    "der Kompromiss": "компромисс",
    "der Kundendienst": "обслуживание клиентов",
    "der Kunde": "клиент",
    "der Mangel": "недостаток",
    "der Nachteil": "недостаток",
    "der Nutzen": "польза",
    "der Schaden": "ущерб",
    "der Schutz": "защита",
    "der Standpunkt": "точка зрения",
    "der Streit": "спор",
    "der Tipp": "совет",
    "der Umgang": "обращение",
    "der Umstand": "обстоятельство",
    "der Verlust": "потеря",
    "der Vorteil": "преимущество",
    "der Wandel": "изменение",
    "der Zweifel": "сомнение",
}

